name: Interrogate documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    
    - uses: actions/checkout@v2
      ref: ${{ env.GITHUB_REF_SLUG }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Python Interrogate Check
      uses: JackMcKew/python-interrogate-check@main
      with:
        path: 'pymessagelib'
        badge-location: 'badges/interrogate_badge.svg'

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add badges/interrogate_badge.svg
        git commit -m "Update interrogate_badge.svg" -a || true

    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: refs/heads/${{ env.GITHUB_REF_SLUG }}
        directory: badges/
